/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PolicyCategory = IDL.Variant({
  'motor' : IDL.Null,
  'otherGeneral' : IDL.Null,
  'travel' : IDL.Null,
  'life' : IDL.Null,
  'termPlan' : IDL.Null,
  'health' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Policy = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'category' : PolicyCategory,
  'benefits' : IDL.Text,
  'coverage' : IDL.Text,
  'price' : IDL.Float64,
});
export const PolicyIssuanceConfirmation = IDL.Record({
  'rewardAmount' : IDL.Float64,
  'policyId' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'referralCode' : IDL.Text,
  'name' : IDL.Text,
  'referredBy' : IDL.Opt(IDL.Text),
  'mobile' : IDL.Opt(IDL.Text),
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'message' : IDL.Text,
  'category' : PolicyCategory,
});
export const CustomerDetails = IDL.Record({
  'contactTime' : IDL.Text,
  'name' : IDL.Text,
  'notes' : IDL.Text,
  'mobile' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addNotification' : IDL.Func([IDL.Text, PolicyCategory], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'comparePolicies' : IDL.Func(
      [IDL.Vec(IDL.Nat)],
      [IDL.Vec(Policy)],
      ['query'],
    ),
  'confirmPolicyIssuance' : IDL.Func(
      [IDL.Nat],
      [PolicyIssuanceConfirmation],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPoliciesByCategory' : IDL.Func(
      [PolicyCategory],
      [IDL.Vec(Policy)],
      ['query'],
    ),
  'getPolicy' : IDL.Func([IDL.Nat], [Policy], ['query']),
  'getRewards' : IDL.Func([], [IDL.Float64], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'requestCallback' : IDL.Func([CustomerDetails], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitLead' : IDL.Func([IDL.Nat, CustomerDetails], [IDL.Nat], []),
  'updateRewardPercentage' : IDL.Func([IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PolicyCategory = IDL.Variant({
    'motor' : IDL.Null,
    'otherGeneral' : IDL.Null,
    'travel' : IDL.Null,
    'life' : IDL.Null,
    'termPlan' : IDL.Null,
    'health' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Policy = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'category' : PolicyCategory,
    'benefits' : IDL.Text,
    'coverage' : IDL.Text,
    'price' : IDL.Float64,
  });
  const PolicyIssuanceConfirmation = IDL.Record({
    'rewardAmount' : IDL.Float64,
    'policyId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'referralCode' : IDL.Text,
    'name' : IDL.Text,
    'referredBy' : IDL.Opt(IDL.Text),
    'mobile' : IDL.Opt(IDL.Text),
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'message' : IDL.Text,
    'category' : PolicyCategory,
  });
  const CustomerDetails = IDL.Record({
    'contactTime' : IDL.Text,
    'name' : IDL.Text,
    'notes' : IDL.Text,
    'mobile' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addNotification' : IDL.Func([IDL.Text, PolicyCategory], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'comparePolicies' : IDL.Func(
        [IDL.Vec(IDL.Nat)],
        [IDL.Vec(Policy)],
        ['query'],
      ),
    'confirmPolicyIssuance' : IDL.Func(
        [IDL.Nat],
        [PolicyIssuanceConfirmation],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPoliciesByCategory' : IDL.Func(
        [PolicyCategory],
        [IDL.Vec(Policy)],
        ['query'],
      ),
    'getPolicy' : IDL.Func([IDL.Nat], [Policy], ['query']),
    'getRewards' : IDL.Func([], [IDL.Float64], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'requestCallback' : IDL.Func([CustomerDetails], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitLead' : IDL.Func([IDL.Nat, CustomerDetails], [IDL.Nat], []),
    'updateRewardPercentage' : IDL.Func([IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };