/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CustomerDetails {
  'contactTime' : string,
  'name' : string,
  'notes' : string,
  'mobile' : string,
}
export interface Notification {
  'id' : bigint,
  'message' : string,
  'category' : PolicyCategory,
}
export interface Policy {
  'id' : bigint,
  'name' : string,
  'category' : PolicyCategory,
  'benefits' : string,
  'coverage' : string,
  'price' : number,
}
export type PolicyCategory = { 'motor' : null } |
  { 'otherGeneral' : null } |
  { 'travel' : null } |
  { 'life' : null } |
  { 'termPlan' : null } |
  { 'health' : null };
export interface PolicyIssuanceConfirmation {
  'rewardAmount' : number,
  'policyId' : bigint,
}
export interface UserProfile {
  'referralCode' : string,
  'name' : string,
  'referredBy' : [] | [string],
  'mobile' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addNotification' : ActorMethod<[string, PolicyCategory], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'comparePolicies' : ActorMethod<[Array<bigint>], Array<Policy>>,
  'confirmPolicyIssuance' : ActorMethod<[bigint], PolicyIssuanceConfirmation>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPoliciesByCategory' : ActorMethod<[PolicyCategory], Array<Policy>>,
  'getPolicy' : ActorMethod<[bigint], Policy>,
  'getRewards' : ActorMethod<[], number>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'requestCallback' : ActorMethod<[CustomerDetails], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitLead' : ActorMethod<[bigint, CustomerDetails], bigint>,
  'updateRewardPercentage' : ActorMethod<[number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];