/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PolicyIssuanceConfirmation {
    rewardAmount: number;
    policyId: bigint;
}
export interface Notification {
    id: bigint;
    message: string;
    category: PolicyCategory;
}
export interface Policy {
    id: bigint;
    name: string;
    category: PolicyCategory;
    benefits: string;
    coverage: string;
    price: number;
}
export interface UserProfile {
    referralCode: string;
    name: string;
    referredBy?: string;
    mobile?: string;
}
export interface CustomerDetails {
    contactTime: string;
    name: string;
    notes: string;
    mobile: string;
}
export enum PolicyCategory {
    motor = "motor",
    otherGeneral = "otherGeneral",
    travel = "travel",
    life = "life",
    termPlan = "termPlan",
    health = "health"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addNotification(message: string, category: PolicyCategory): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    comparePolicies(policyIds: Array<bigint>): Promise<Array<Policy>>;
    confirmPolicyIssuance(leadId: bigint): Promise<PolicyIssuanceConfirmation>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getNotifications(): Promise<Array<Notification>>;
    getPoliciesByCategory(category: PolicyCategory): Promise<Array<Policy>>;
    getPolicy(policyId: bigint): Promise<Policy>;
    getRewards(): Promise<number>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    requestCallback(customerDetails: CustomerDetails): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitLead(policyId: bigint, customerDetails: CustomerDetails): Promise<bigint>;
    updateRewardPercentage(newPercentage: number): Promise<void>;
}
import type { Notification as _Notification, Policy as _Policy, PolicyCategory as _PolicyCategory, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addNotification(arg0: string, arg1: PolicyCategory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addNotification(arg0, to_candid_PolicyCategory_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNotification(arg0, to_candid_PolicyCategory_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async comparePolicies(arg0: Array<bigint>): Promise<Array<Policy>> {
        if (this.processError) {
            try {
                const result = await this.actor.comparePolicies(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.comparePolicies(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async confirmPolicyIssuance(arg0: bigint): Promise<PolicyIssuanceConfirmation> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmPolicyIssuance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmPolicyIssuance(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPoliciesByCategory(arg0: PolicyCategory): Promise<Array<Policy>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPoliciesByCategory(to_candid_PolicyCategory_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPoliciesByCategory(to_candid_PolicyCategory_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPolicy(arg0: bigint): Promise<Policy> {
        if (this.processError) {
            try {
                const result = await this.actor.getPolicy(arg0);
                return from_candid_Policy_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPolicy(arg0);
            return from_candid_Policy_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRewards(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getRewards();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRewards();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async requestCallback(arg0: CustomerDetails): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.requestCallback(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestCallback(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitLead(arg0: bigint, arg1: CustomerDetails): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitLead(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitLead(arg0, arg1);
            return result;
        }
    }
    async updateRewardPercentage(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRewardPercentage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRewardPercentage(arg0);
            return result;
        }
    }
}
function from_candid_Notification_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_PolicyCategory_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PolicyCategory): PolicyCategory {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Policy_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Policy): Policy {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    referralCode: string;
    name: string;
    referredBy: [] | [string];
    mobile: [] | [string];
}): {
    referralCode: string;
    name: string;
    referredBy?: string;
    mobile?: string;
} {
    return {
        referralCode: value.referralCode,
        name: value.name,
        referredBy: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.referredBy)),
        mobile: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.mobile))
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    message: string;
    category: _PolicyCategory;
}): {
    id: bigint;
    message: string;
    category: PolicyCategory;
} {
    return {
        id: value.id,
        message: value.message,
        category: from_candid_PolicyCategory_n8(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    category: _PolicyCategory;
    benefits: string;
    coverage: string;
    price: number;
}): {
    id: bigint;
    name: string;
    category: PolicyCategory;
    benefits: string;
    coverage: string;
    price: number;
} {
    return {
        id: value.id,
        name: value.name,
        category: from_candid_PolicyCategory_n8(_uploadFile, _downloadFile, value.category),
        benefits: value.benefits,
        coverage: value.coverage,
        price: value.price
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    motor: null;
} | {
    otherGeneral: null;
} | {
    travel: null;
} | {
    life: null;
} | {
    termPlan: null;
} | {
    health: null;
}): PolicyCategory {
    return "motor" in value ? PolicyCategory.motor : "otherGeneral" in value ? PolicyCategory.otherGeneral : "travel" in value ? PolicyCategory.travel : "life" in value ? PolicyCategory.life : "termPlan" in value ? PolicyCategory.termPlan : "health" in value ? PolicyCategory.health : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Policy>): Array<Policy> {
    return value.map((x)=>from_candid_Policy_n6(_uploadFile, _downloadFile, x));
}
function to_candid_PolicyCategory_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PolicyCategory): _PolicyCategory {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    referralCode: string;
    name: string;
    referredBy?: string;
    mobile?: string;
}): {
    referralCode: string;
    name: string;
    referredBy: [] | [string];
    mobile: [] | [string];
} {
    return {
        referralCode: value.referralCode,
        name: value.name,
        referredBy: value.referredBy ? candid_some(value.referredBy) : candid_none(),
        mobile: value.mobile ? candid_some(value.mobile) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PolicyCategory): {
    motor: null;
} | {
    otherGeneral: null;
} | {
    travel: null;
} | {
    life: null;
} | {
    termPlan: null;
} | {
    health: null;
} {
    return value == PolicyCategory.motor ? {
        motor: null
    } : value == PolicyCategory.otherGeneral ? {
        otherGeneral: null
    } : value == PolicyCategory.travel ? {
        travel: null
    } : value == PolicyCategory.life ? {
        life: null
    } : value == PolicyCategory.termPlan ? {
        termPlan: null
    } : value == PolicyCategory.health ? {
        health: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
